mod context;
mod context_async;
pub(crate) mod types;

use pyo3::prelude::*;

pub(crate) fn register_types(parent: &Bound<PyModule>) -> PyResult<()> {
    use types::*;
    parent.add_class::<InstitutionRecommend>()?;
    parent.add_class::<FinancialReports>()?;
    parent.add_class::<DividendList>()?;
    parent.add_class::<DividendItem>()?;
    parent.add_class::<InstitutionRating>()?;
    parent.add_class::<InstitutionRatingLatest>()?;
    parent.add_class::<RatingEvaluate>()?;
    parent.add_class::<RatingTarget>()?;
    parent.add_class::<InstitutionRatingSummary>()?;
    parent.add_class::<RatingSummaryEvaluate>()?;
    parent.add_class::<InstitutionRatingDetail>()?;
    parent.add_class::<InstitutionRatingDetailEvaluate>()?;
    parent.add_class::<InstitutionRatingDetailEvaluateItem>()?;
    parent.add_class::<InstitutionRatingDetailTarget>()?;
    parent.add_class::<InstitutionRatingDetailTargetItem>()?;
    parent.add_class::<ForecastEps>()?;
    parent.add_class::<ForecastEpsItem>()?;
    parent.add_class::<FinancialConsensus>()?;
    parent.add_class::<ConsensusReport>()?;
    parent.add_class::<ConsensusDetail>()?;
    parent.add_class::<ValuationData>()?;
    parent.add_class::<ValuationMetricsData>()?;
    parent.add_class::<ValuationMetricData>()?;
    parent.add_class::<ValuationPoint>()?;
    parent.add_class::<ValuationHistoryResponse>()?;
    parent.add_class::<ValuationHistoryData>()?;
    parent.add_class::<ValuationHistoryMetrics>()?;
    parent.add_class::<ValuationHistoryMetric>()?;
    parent.add_class::<IndustryValuationList>()?;
    parent.add_class::<IndustryValuationItem>()?;
    parent.add_class::<IndustryValuationHistory>()?;
    parent.add_class::<IndustryValuationDist>()?;
    parent.add_class::<ValuationDist>()?;
    parent.add_class::<CompanyOverview>()?;
    parent.add_class::<ExecutiveList>()?;
    parent.add_class::<ExecutiveGroup>()?;
    parent.add_class::<Professional>()?;
    parent.add_class::<ShareholderList>()?;
    parent.add_class::<Shareholder>()?;
    parent.add_class::<ShareholderStock>()?;
    parent.add_class::<FundHolders>()?;
    parent.add_class::<FundHolder>()?;
    parent.add_class::<CorpActions>()?;
    parent.add_class::<CorpActionItem>()?;
    parent.add_class::<CorpActionLive>()?;
    parent.add_class::<InvestRelations>()?;
    parent.add_class::<InvestSecurity>()?;
    parent.add_class::<OperatingList>()?;
    parent.add_class::<OperatingItem>()?;
    parent.add_class::<OperatingFinancial>()?;
    parent.add_class::<OperatingIndicator>()?;
    parent.add_class::<FinancialReportKind>()?;
    parent.add_class::<FinancialReportPeriod>()?;
    parent.add_class::<RecentBuybacks>()?;
    parent.add_class::<BuybackHistoryItem>()?;
    parent.add_class::<BuybackRatios>()?;
    parent.add_class::<BuybackData>()?;
    parent.add_class::<StockRatings>()?;
    parent.add_class::<ShareholderTopResponse>()?;
    parent.add_class::<ShareholderDetailResponse>()?;
    parent.add_class::<ValuationHistoryPoint>()?;
    parent.add_class::<ValuationComparisonItem>()?;
    parent.add_class::<ValuationComparisonResponse>()?;
    parent.add_class::<ElementType>()?;
    parent.add_class::<HoldingDetail>()?;
    parent.add_class::<AssetAllocationItem>()?;
    parent.add_class::<AssetAllocationGroup>()?;
    parent.add_class::<AssetAllocationResponse>()?;
    parent.add_class::<MultiLanguageText>()?;
    parent.add_class::<MacroeconomicCountry>()?;
    parent.add_class::<MacroeconomicIndicatorListResponse>()?;
    parent.add_class::<MacroeconomicIndicator>()?;
    parent.add_class::<Macroeconomic>()?;
    parent.add_class::<MacroeconomicResponse>()?;
    parent.add_class::<context::FundamentalContext>()?;
    parent.add_class::<context_async::AsyncFundamentalContext>()?;
    Ok(())
}
