extend = [
    { path = "rust/Makefile.toml" },
    { path = "python/Makefile.toml" },
    { path = "java/Makefile.toml" },
    { path = "c/Makefile.toml" },
    { path = "cpp/Makefile.toml" },
]

[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.default]

[tasks.create-cmake-build-dir]
command = "cmake"
args = ["-E", "make_directory", "cmake.build"]

[tasks.cmake]
command = "cmake"
args = ["../"]
cwd = "cmake.build"
dependencies = ["create-cmake-build-dir"]

[tasks.cmake-release]
command = "cmake"
args = ["-DCMAKE_BUILD_TYPE=Release", "../"]
cwd = "cmake.build"
dependencies = ["create-cmake-build-dir"]

[tasks.cmake-release.windows]
command = "cmake"
args = ["../"]
cwd = "cmake.build"

[tasks.cmake-release-macos-aarch64]
command = "cmake"
args = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DRust_CARGO_TARGET=aarch64-apple-darwin",
    "-DCMAKE_OSX_ARCHITECTURES=arm64",
    "../",
]
cwd = "cmake.build"
dependencies = ["create-cmake-build-dir"]

[tasks.cmake-debug]
command = "cmake"
args = ["-DCMAKE_BUILD_TYPE=Debug", "../"]
cwd = "cmake.build"
dependencies = ["create-cmake-build-dir"]

[tasks.cmake-debug.windows]
command = "cmake"
args = ["../"]
cwd = "cmake.build"

[tasks.cmake-debug-macos-aarch64]
command = "cmake"
args = [
    "-DCMAKE_BUILD_TYPE=Debug",
    "-DRust_CARGO_TARGET=aarch64-apple-darwin",
    "-DCMAKE_OSX_ARCHITECTURES=arm64",
    "../",
]
cwd = "cmake.build"
dependencies = ["create-cmake-build-dir"]
