/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_longport_SdkNative */

#ifndef _Included_com_longport_SdkNative
#define _Included_com_longport_SdkNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_longport_SdkNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_init
  (JNIEnv *, jclass);

/*
 * Class:     com_longport_SdkNative
 * Method:    newHttpClientFromApikey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newHttpClientFromApikey
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    newHttpClientFromApikeyEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newHttpClientFromApikeyEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_longport_SdkNative
 * Method:    newHttpClientFromOauth
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newHttpClientFromOauth
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeHttpClient
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeHttpClient
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    httpClientRequest
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_httpClientRequest
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newConfigFromApikey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newConfigFromApikey
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    newConfigFromApikeyEnv
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newConfigFromApikeyEnv
  (JNIEnv *, jclass);

/*
 * Class:     com_longport_SdkNative
 * Method:    newConfigFromOauth
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newConfigFromOauth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetHttpUrl
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetHttpUrl
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetQuoteWsUrl
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetQuoteWsUrl
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetTradeWsUrl
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetTradeWsUrl
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetLanguage
 * Signature: (JLcom/longport/Language;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetLanguage
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetEnableOvernight
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetEnableOvernight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetPushCandlestickMode
 * Signature: (JLcom/longport/PushCandlestickMode;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetPushCandlestickMode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetEnablePrintQuotePackages
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetEnablePrintQuotePackages
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_longport_SdkNative
 * Method:    configSetLogPath
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_configSetLogPath
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_longport_SdkNative
 * Method:    configRefreshAccessToken
 * Signature: (JLjava/time/OffsetDateTime;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_configRefreshAccessToken
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    oauthBuild
 * Signature: (Ljava/lang/String;ILjava/util/function/Consumer;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_oauthBuild
  (JNIEnv *, jclass, jstring, jint, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeOAuth
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeOAuth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    newAssetContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newAssetContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeAssetContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeAssetContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    assetContextStatements
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_assetContextStatements
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    assetContextDownloadUrl
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_assetContextDownloadUrl
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newContentContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newContentContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeContentContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeContentContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    contentContextMyTopics
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_contentContextMyTopics
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    contentContextCreateTopic
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_contentContextCreateTopic
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    contentContextTopics
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_contentContextTopics
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    contentContextNews
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_contentContextNews
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newQuoteContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newQuoteContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeQuoteContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeQuoteContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextGetMemberId
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextGetMemberId
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextGetQuoteLevel
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextGetQuoteLevel
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextGetQuotePackageDetails
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextGetQuotePackageDetails
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSetOnQuote
 * Signature: (JLcom/longport/quote/QuoteHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSetOnQuote
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSetOnDepth
 * Signature: (JLcom/longport/quote/DepthHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSetOnDepth
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSetOnBrokers
 * Signature: (JLcom/longport/quote/BrokersHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSetOnBrokers
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSetOnTrades
 * Signature: (JLcom/longport/quote/TradesHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSetOnTrades
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSetOnCandlestick
 * Signature: (JLcom/longport/quote/CandlestickHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSetOnCandlestick
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSubscribe
 * Signature: (J[Ljava/lang/String;ILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextUnsubscribe
 * Signature: (J[Ljava/lang/String;ILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextUnsubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSubscribeCandlesticks
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;Lcom/longport/quote/TradeSessions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSubscribeCandlesticks
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextUnsubscribeCandlesticks
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextUnsubscribeCandlesticks
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSubscriptions
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSubscriptions
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextStaticInfo
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextStaticInfo
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextQuote
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextOptionQuote
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextOptionQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextWarrantQuote
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextWarrantQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextDepth
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextDepth
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextBrokers
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextBrokers
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextParticipants
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextParticipants
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextTrades
 * Signature: (JLjava/lang/String;ILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextTrades
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextIntraday
 * Signature: (JLjava/lang/String;Lcom/longport/quote/TradeSessions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextIntraday
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextCandlesticks
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;ILcom/longport/quote/AdjustType;Lcom/longport/quote/TradeSessions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextCandlesticks
  (JNIEnv *, jclass, jlong, jstring, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextHistoryCandlesticksByOffset
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;Lcom/longport/quote/AdjustType;ZLjava/time/LocalDateTime;ILcom/longport/quote/TradeSessions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextHistoryCandlesticksByOffset
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject, jboolean, jobject, jint, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextHistoryCandlesticksByDate
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;Lcom/longport/quote/AdjustType;Ljava/time/LocalDate;Ljava/time/LocalDate;Lcom/longport/quote/TradeSessions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextHistoryCandlesticksByDate
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextOptionChainExpiryDateList
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextOptionChainExpiryDateList
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextOptionChainInfoByDate
 * Signature: (JLjava/lang/String;Ljava/time/LocalDate;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextOptionChainInfoByDate
  (JNIEnv *, jclass, jlong, jstring, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextWarrantIssuers
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextWarrantIssuers
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextWarrantList
 * Signature: (JLcom/longport/quote/QueryWarrantOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextWarrantList
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextTradingSession
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextTradingSession
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextTradingDays
 * Signature: (JLcom/longport/Market;Ljava/time/LocalDate;Ljava/time/LocalDate;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextTradingDays
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextCapitalFlow
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextCapitalFlow
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextCapitalDistribution
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextCapitalDistribution
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextCalcIndexes
 * Signature: (J[Ljava/lang/String;[Lcom/longport/quote/CalcIndex;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextCalcIndexes
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextWatchlist
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextWatchlist
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextCreateWatchlistGroup
 * Signature: (JLcom/longport/quote/CreateWatchlistGroup;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextCreateWatchlistGroup
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextDeleteWatchlistGroup
 * Signature: (JLcom/longport/quote/DeleteWatchlistGroup;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextDeleteWatchlistGroup
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextUpdateWatchlistGroup
 * Signature: (JLcom/longport/quote/UpdateWatchlistGroup;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextUpdateWatchlistGroup
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextFilings
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextFilings
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextSecurityList
 * Signature: (JLcom/longport/Market;Lcom/longport/quote/SecurityListCategory;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextSecurityList
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextMarketTemperature
 * Signature: (JLcom/longport/Market;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextMarketTemperature
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextHistoryMarketTemperature
 * Signature: (JLcom/longport/Market;Ljava/time/LocalDate;Ljava/time/LocalDate;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextHistoryMarketTemperature
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextRealtimeQuote
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextRealtimeQuote
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextRealtimeDepth
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextRealtimeDepth
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextRealtimeBrokers
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextRealtimeBrokers
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextRealtimeTrades
 * Signature: (JLjava/lang/String;ILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextRealtimeTrades
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextRealtimeCandlesticks
 * Signature: (JLjava/lang/String;Lcom/longport/quote/Period;ILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextRealtimeCandlesticks
  (JNIEnv *, jclass, jlong, jstring, jobject, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newTradeContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newTradeContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeTradeContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeTradeContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextSetOnOrderChanged
 * Signature: (JLcom/longport/trade/OrderChangedHandler;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextSetOnOrderChanged
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextSubscribe
 * Signature: (J[Lcom/longport/trade/TopicType;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextSubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextUnsubscribe
 * Signature: (J[Lcom/longport/trade/TopicType;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextUnsubscribe
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextHistoryExecutions
 * Signature: (JLcom/longport/trade/GetHistoryExecutionsOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextHistoryExecutions
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextTodayExecutions
 * Signature: (JLcom/longport/trade/GetTodayExecutionsOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextTodayExecutions
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextHistoryOrders
 * Signature: (JLcom/longport/trade/GetHistoryOrdersOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextHistoryOrders
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextTodayOrders
 * Signature: (JLcom/longport/trade/GetTodayOrdersOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextTodayOrders
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextReplaceOrder
 * Signature: (JLcom/longport/trade/ReplaceOrderOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextReplaceOrder
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextSubmitOrder
 * Signature: (JLcom/longport/trade/SubmitOrderOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextSubmitOrder
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextCancelOrder
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextCancelOrder
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextAccountBalance
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextAccountBalance
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextCashFlow
 * Signature: (JLcom/longport/trade/GetCashFlowOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextCashFlow
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextFundPositions
 * Signature: (JLcom/longport/trade/GetFundPositionsOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextFundPositions
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextStockPositions
 * Signature: (JLcom/longport/trade/GetStockPositionsOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextStockPositions
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextMarginRatio
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextMarginRatio
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextOrderDetail
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextOrderDetail
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    tradeContextEstimateMaxPurchaseQuantity
 * Signature: (JLcom/longport/trade/EstimateMaxPurchaseQuantityOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_tradeContextEstimateMaxPurchaseQuantity
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newDcaContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newDcaContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeDcaContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeDcaContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextList
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextList
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextStats
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextStats
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextCheckSupport
 * Signature: (J[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextCheckSupport
  (JNIEnv *, jclass, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextHistory
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextHistory
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextPause
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextPause
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextResume
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextResume
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextStop
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextStop
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextCalcDate
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextCalcDate
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextSetReminder
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextSetReminder
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextCreate
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextCreate
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    dcaContextUpdate
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_dcaContextUpdate
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newSharelistContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newSharelistContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeSharelistContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeSharelistContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextList
 * Signature: (JILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextList
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextDetail
 * Signature: (JJLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextDetail
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextPopular
 * Signature: (JILcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextPopular
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextCreate
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextCreate
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextAddSecurities
 * Signature: (JJ[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextAddSecurities
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextRemoveSecurities
 * Signature: (JJ[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextRemoveSecurities
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextSortSecurities
 * Signature: (JJ[Ljava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextSortSecurities
  (JNIEnv *, jclass, jlong, jlong, jobjectArray, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    sharelistContextDelete
 * Signature: (JJLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_sharelistContextDelete
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newAlertContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newAlertContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeAlertContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeAlertContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    alertContextList
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_alertContextList
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    alertContextAdd
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_alertContextAdd
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    alertContextEnable
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_alertContextEnable
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    alertContextDisable
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_alertContextDisable
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    alertContextDelete
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_alertContextDelete
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newCalendarContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newCalendarContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeCalendarContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeCalendarContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    calendarContextFinanceCalendar
 * Signature: (JLcom/longport/calendar/FinanceCalendarOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_calendarContextFinanceCalendar
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newPortfolioContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newPortfolioContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freePortfolioContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freePortfolioContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    portfolioContextExchangeRate
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_portfolioContextExchangeRate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    portfolioContextProfitAnalysis
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_portfolioContextProfitAnalysis
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    portfolioContextProfitAnalysisDetail
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_portfolioContextProfitAnalysisDetail
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    portfolioContextProfitAnalysisByMarket
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_portfolioContextProfitAnalysisByMarket
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextShortPositions
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextShortPositions
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextOptionVolume
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextOptionVolume
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextOptionVolumeDaily
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextOptionVolumeDaily
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newMarketContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newMarketContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeMarketContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeMarketContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextMarketStatus
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextMarketStatus
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextBrokerHolding
 * Signature: (JLcom/longport/market/BrokerHoldingOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextBrokerHolding
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextBrokerHoldingDetail
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextBrokerHoldingDetail
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextBrokerHoldingDaily
 * Signature: (JLcom/longport/market/BrokerHoldingDailyOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextBrokerHoldingDaily
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextAhPremium
 * Signature: (JLcom/longport/market/AhPremiumOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextAhPremium
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextAhPremiumIntraday
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextAhPremiumIntraday
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextTradeStats
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextTradeStats
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextAnomaly
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextAnomaly
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextConstituent
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextConstituent
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextTopMovers
 * Signature: (JLcom/longport/market/TopMoversOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextTopMovers
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextRankCategories
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextRankCategories
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    marketContextRankList
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_marketContextRankList
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newScreenerContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newScreenerContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeScreenerContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeScreenerContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    screenerContextRecommendStrategies
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_screenerContextRecommendStrategies
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    screenerContextUserStrategies
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_screenerContextUserStrategies
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    screenerContextStrategy
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_screenerContextStrategy
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    screenerContextSearch
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_screenerContextSearch
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    screenerContextIndicators
 * Signature: (JLcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_screenerContextIndicators
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextShareholderTop
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextShareholderTop
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextShareholderDetail
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextShareholderDetail
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextValuationComparison
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextValuationComparison
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextShortTrades
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextShortTrades
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    newFundamentalContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_longport_SdkNative_newFundamentalContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    freeFundamentalContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_freeFundamentalContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextFinancialReport
 * Signature: (JLcom/longport/fundamental/FinancialReportOptions;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextFinancialReport
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextInstitutionRating
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextInstitutionRating
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextInstitutionRatingDetail
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextInstitutionRatingDetail
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextDividend
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextDividend
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextDividendDetail
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextDividendDetail
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextForecastEps
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextForecastEps
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextConsensus
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextConsensus
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextValuation
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextValuation
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextValuationHistory
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextValuationHistory
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextIndustryValuation
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextIndustryValuation
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextIndustryValuationDist
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextIndustryValuationDist
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextCompany
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextCompany
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextExecutive
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextExecutive
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextShareholder
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextShareholder
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextFundHolder
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextFundHolder
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextCorpAction
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextCorpAction
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextInvestRelation
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextInvestRelation
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextOperating
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextOperating
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetBuyback
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetBuyback
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetRatings
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetRatings
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetBusinessSegments
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetBusinessSegments
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetBusinessSegmentsHistory
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetBusinessSegmentsHistory
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetInstitutionRatingViews
 * Signature: (JLjava/lang/String;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetInstitutionRatingViews
  (JNIEnv *, jclass, jlong, jstring, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetIndustryRank
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetIndustryRank
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetIndustryPeers
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetIndustryPeers
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextGetFinancialReportSnapshot
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextGetFinancialReportSnapshot
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextMacroeconomicIndicators
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextMacroeconomicIndicators
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    fundamentalContextMacroeconomic
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_fundamentalContextMacroeconomic
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    portfolioContextProfitAnalysisFlows
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_portfolioContextProfitAnalysisFlows
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_longport_SdkNative
 * Method:    quoteContextUpdatePinned
 * Signature: (JLjava/lang/Object;Lcom/longport/AsyncCallback;)V
 */
JNIEXPORT void JNICALL Java_com_longport_SdkNative_quoteContextUpdatePinned
  (JNIEnv *, jclass, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
