[package]
name = "longport-java-macros"
version = "3.0.12"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.20.10"
proc-macro2 = "1.0.29"
quote = "1.0.9"
syn = { version = "2.0.77", features = ["parsing"] }
thiserror = "1.0.29"
